import type { CSSProperties } from 'react';

// Inline styles for content script - ensures no conflicts with host page
export const classes = {
    modalContainer: {
        position: 'fixed',
        bottom: '80px',
        right: '20px',
        zIndex: 2147483647,
        backgroundColor: '#ffffff',
        border: '1px solid #e5e7eb',
        borderRadius: '12px',
        boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        padding: '12px 8px',
        minWidth: '100px',
        maxWidth: '400px',
        fontFamily: "Inter, system-ui, -apple-system, sans-serif",
        fontSize: '14px',
        lineHeight: '1.5',
        color: '#1f2937',
        backdropFilter: 'blur(8px)',
        WebkitBackdropFilter: 'blur(8px)',
        animation: 'summer-slide-in 0.3s ease-out',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '12px',
    } as CSSProperties,

    title: {
        fontSize: '18px',
        fontWeight: '600',
        margin: '0 0 12px 0',
        color: '#111827',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    } as CSSProperties,

    text: {
        color: '#6b7280',
        margin: '0 0 16px 0',
        fontSize: '14px',
        lineHeight: '1.6',
    } as CSSProperties,

    button: {
        backgroundColor: '#3b82f6',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        padding: '12px 20px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '500',
        width: '100%',
        transition: 'all 0.2s ease',
        fontFamily: 'inherit',
    } as CSSProperties,

    plainButton: {
        backgroundColor: 'transparent',
        border: 'none',
        cursor: 'pointer',
        fontSize: '16px',
        fontWeight: '500',
        padding: '8px',
        borderRadius: '8px',
        transition: 'all 0.2s ease',
        fontFamily: 'inherit',
        color: '#6b7280',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: '36px',
        minHeight: '36px',
    } as CSSProperties,

    closeButton: {
        position: 'absolute',
        top: '12px',
        right: '12px',
        backgroundColor: 'transparent',
        border: 'none',
        cursor: 'pointer',
        padding: '4px',
        borderRadius: '6px',
        color: '#9ca3af',
        fontSize: '16px',
        lineHeight: '1',
        transition: 'all 0.2s ease',
    } as CSSProperties,

    badge: {
        backgroundColor: '#f0f9ff',
        color: '#0369a1',
        padding: '2px 8px',
        borderRadius: '12px',
        fontSize: '12px',
        fontWeight: '500',
    } as CSSProperties,

    optionsContainer: {
        display: 'flex',
        flexDirection: 'row',
        gap: '8px',
    } as CSSProperties,

    tooltip: {
        position: 'fixed',
        backgroundColor: '#1f2937',
        color: 'white',
        padding: '6px 10px',
        borderRadius: '6px',
        fontSize: '12px',
        fontWeight: '500',
        whiteSpace: 'nowrap',
        zIndex: 2147483648,
        opacity: 0,
        transition: 'opacity 0.2s ease',
        pointerEvents: 'none',
        fontFamily: 'system-ui, -apple-system, sans-serif',
    } as CSSProperties,

    tooltipVisible: {
        opacity: 1,
    } as CSSProperties,
};