// SUMMARIZER API TYPES
// Based on https://developer.mozilla.org/en-US/docs/Web/API/Summarizer
interface Window {
  Summarizer: Summarizer;
}

/**
 * Summarizer interface, including all related summarization functions
 * Including checking AI model availability, creating new Summarizer instances, and performing summaries.
 */
declare interface Summarizer {
  /**
   * Check the availability of the AI model
   * @returns an enumerated value that indicates the availability of the AI model
   */
  availability: (options: SummarizerAvailabilityOptions) => Promise<SummarizerAvailability>;

  /**
   * Creates a new Summarizer instance
   * @param options configuration options
   * @returns Summarizer instance
   */
  create: (options?: SummarizerCreateOptions) => Promise<SummarizerInstance>;
}

/**
 * Availability Options for Summarizer instances
 */
declare interface SummarizerAvailabilityOptions {
  /** the expected languages of the input text */
  expectedInputLanguages: string[];
  /** the expected languages of any provided context strings */
  expectedContextLanguages: string[];
  /** An enumerated value specifying the text format */
  format: 'plain-text' | 'markdown';
  /** An enumerated value specifying the relative length */
  length: 'short' | 'medium' | 'long';
  /** the expected language of summaries generated by the Summarizer */
  outputLanguage: string;
  /** An enumerated value specifying the type of summary */
  type: 'headline' | 'key-points' | 'teaser' | 'tldr';
}

/**
 * Create Options for Summarizer instances
 */
declare interface SummarizerCreateOptions extends SummarizerAvailabilityOptions {
  /** A function to be called to monitor the download progress of the model. */
  monitor?: (monitor: SummarizerMonitor) => void;
  /** the context the pieces of text to summarize */
  sharedContext?: string;
  /** An AbortSignal to abort the creation process. */
  signal?: AbortSignal;
}

/**
 * Summarizer availability enumeration
 */
declare type SummarizerAvailability =
  | 'available' // The browser supports and is ready to use
  | 'downloadable' // The browser supports but requires downloading the AI model first
  | 'downloading' // The browser supports but needs to complete an ongoing download
  | 'unavailable'; // The browser does not support the given configuration

/**
 * Summarizer monitor interface for listening to download progress
 */
declare interface SummarizerMonitor extends EventTarget {
  /**
   * Add download progress event listener
   * @param type Event type
   * @param listener Event listener
   */
  addEventListener: (
    type: 'downloadprogress',
    listener: (event: SummarizerDownloadProgressEvent) => void
  ) => void;
}

/**
 * Download progress event
 */
declare interface SummarizerDownloadProgressEvent extends Event {
  /** The percentage downloaded (a value between 0 and 1) */
  readonly loaded: number;
}

/**
 * Summarizer instance interface
 */
declare interface SummarizerInstance {
  /**
   * Destroys the current Summarizer instance
   * It is recommended to call this method when no longer in use, as the instance consumes significant resources
   * @returns No return value (undefined)
   */
  destroy: () => void;

  /**
   * Returns a string containing the summary of the input string
   * @param text The text string to summarize
   * @param options Optional configuration options
   * @returns A Promise that resolves to the summarized result string
   * @throws {InvalidStateError} Thrown when the current Document is not active
   * @throws {NotAllowedError} Thrown when the Summarizer API is blocked by a permissions policy
   * @throws {UnknownError} Other unknown errors
   */
  summarize: (text: string, options?: SummarizerOperationOptions) => Promise<string>;

  /**
   * Generates a summary of the input string as a ReadableStream
   * @param text The text string to summarize
   * @param options Optional configuration options
   * @returns A ReadableStream containing the generated summary
   * @throws {InvalidStateError} Thrown when the current Document is not active
   * @throws {NotAllowedError} Thrown when the Summarizer API is blocked by a permissions policy
   * @throws {UnknownError} Other unknown errors
   */
  summarizeStreaming: (
    text: string,
    options?: SummarizerOperationOptions
  ) => ReadableStream<string>;
}

/**
 * Optional configuration for summarization operations
 */
declare interface SummarizerOperationOptions {
  /** The desired maximum number of tokens in the output summary. */
  maxTokens?: number;
  /** An AbortSignal to abort the operation. */
  signal?: AbortSignal;
}
